namespace AcademicNetworkUI
{
    partial class MainMenu
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainMenu));
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges3 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            txtMessage = new SiticoneNetCoreUI.SiticoneTextBox();
            btnSend = new SiticoneNetCoreUI.SiticoneImageButton();
            guna2ImageButton1 = new Guna.UI2.WinForms.Guna2ImageButton();
            label1 = new Label();
            panel1 = new Panel();
            panelJoinGroup = new Panel();
            btnCancelJoin = new SiticoneNetCoreUI.SiticoneButton();
            btnConfirmJoin = new SiticoneNetCoreUI.SiticoneButton();
            dgvAvailableGroups = new DataGridView();
            panelCreateGroup = new Panel();
            btnCancelCreateGroup = new SiticoneNetCoreUI.SiticoneButton();
            btnConfirmCreateGroup = new SiticoneNetCoreUI.SiticoneButton();
            txtGroupName = new SiticoneNetCoreUI.SiticoneTextBox();
            btnCreate = new SiticoneNetCoreUI.SiticoneButton();
            dgvGroups = new DataGridView();
            siticoneButton2 = new SiticoneNetCoreUI.SiticoneButton();
            siticoneLabel1 = new SiticoneNetCoreUI.SiticoneLabel();
            panel2 = new Panel();
            lblSelectedGroupID = new Label();
            siticoneCloseButton1 = new SiticoneNetCoreUI.SiticoneCloseButton();
            panel3 = new Panel();
            siticoneImageButton3 = new SiticoneNetCoreUI.SiticoneImageButton();
            lblUsernameDisplay = new Label();
            siticoneImageButton2 = new SiticoneNetCoreUI.SiticoneImageButton();
            rightBtn = new SiticoneNetCoreUI.SiticoneMenuButton();
            panelMembers = new Panel();
            btnKickMember = new SiticoneNetCoreUI.SiticoneButton();
            lstGroupMembers = new ListBox();
            dgvMembers = new DataGridView();
            label3 = new Label();
            panel4 = new Panel();
            btnLeaveGroup = new SiticoneNetCoreUI.SiticoneButton();
            lblGroupNameDisplay = new Label();
            txtNewMessage = new TextBox();
            btnSaveEdit = new SiticoneNetCoreUI.SiticoneButton();
            btnDeleteMessage = new SiticoneNetCoreUI.SiticoneButton();
            btnEditMessage = new SiticoneNetCoreUI.SiticoneButton();
            panel5 = new Panel();
            lstMessages = new ListBox();
            panel1.SuspendLayout();
            panelJoinGroup.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvAvailableGroups).BeginInit();
            panelCreateGroup.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvGroups).BeginInit();
            panel2.SuspendLayout();
            panel3.SuspendLayout();
            panelMembers.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvMembers).BeginInit();
            panel4.SuspendLayout();
            panel5.SuspendLayout();
            SuspendLayout();
            // 
            // txtMessage
            // 
            txtMessage.AccessibleDescription = "A customizable text input field.";
            txtMessage.AccessibleName = "Text Box";
            txtMessage.AccessibleRole = AccessibleRole.Text;
            txtMessage.BackColor = Color.Transparent;
            txtMessage.BlinkCount = 3;
            txtMessage.BlinkShadow = false;
            txtMessage.BorderColor1 = Color.LightSlateGray;
            txtMessage.BorderColor2 = Color.LightSlateGray;
            txtMessage.BorderFocusColor1 = Color.FromArgb(77, 77, 255);
            txtMessage.BorderFocusColor2 = Color.FromArgb(77, 77, 255);
            txtMessage.CanShake = true;
            txtMessage.ContinuousBlink = false;
            txtMessage.CornerRadiusBottomLeft = 10;
            txtMessage.CornerRadiusBottomRight = 10;
            txtMessage.CornerRadiusTopLeft = 10;
            txtMessage.CornerRadiusTopRight = 10;
            txtMessage.CursorBlinkRate = 500;
            txtMessage.CursorColor = Color.Black;
            txtMessage.CursorHeight = 26;
            txtMessage.CursorOffset = 0;
            txtMessage.CursorStyle = SiticoneNetCoreUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            txtMessage.CursorWidth = 1;
            txtMessage.DisabledBackColor = Color.WhiteSmoke;
            txtMessage.DisabledBorderColor = Color.LightGray;
            txtMessage.DisabledTextColor = Color.Gray;
            txtMessage.EnableDropShadow = false;
            txtMessage.FillColor1 = Color.White;
            txtMessage.FillColor2 = Color.White;
            txtMessage.Font = new Font("Segoe UI", 9.5F);
            txtMessage.ForeColor = Color.DimGray;
            txtMessage.HoverBorderColor1 = Color.Gray;
            txtMessage.HoverBorderColor2 = Color.Gray;
            txtMessage.IsEnabled = true;
            txtMessage.Location = new Point(287, 664);
            txtMessage.Name = "txtMessage";
            txtMessage.PlaceholderColor = Color.Gray;
            txtMessage.PlaceholderText = "Enter text here...";
            txtMessage.ReadOnlyBorderColor1 = Color.LightGray;
            txtMessage.ReadOnlyBorderColor2 = Color.LightGray;
            txtMessage.ReadOnlyFillColor1 = Color.WhiteSmoke;
            txtMessage.ReadOnlyFillColor2 = Color.WhiteSmoke;
            txtMessage.ReadOnlyPlaceholderColor = Color.DarkGray;
            txtMessage.SelectionBackColor = Color.FromArgb(77, 77, 255);
            txtMessage.ShadowAnimationDuration = 1;
            txtMessage.ShadowBlur = 10;
            txtMessage.ShadowColor = Color.FromArgb(15, 0, 0, 0);
            txtMessage.Size = new Size(553, 51);
            txtMessage.SolidBorderColor = Color.White;
            txtMessage.SolidBorderFocusColor = Color.FromArgb(77, 77, 255);
            txtMessage.SolidBorderHoverColor = Color.White;
            txtMessage.SolidFillColor = Color.FromArgb(52, 54, 60);
            txtMessage.TabIndex = 1;
            txtMessage.TextPadding = new Padding(16, 0, 6, 0);
            txtMessage.ValidationErrorMessage = "Invalid input.";
            txtMessage.ValidationFunction = null;
            // 
            // btnSend
            // 
            btnSend.AnimationSpeed = 0.15F;
            btnSend.BackColor = Color.Transparent;
            btnSend.BackgroundFillColor = Color.Transparent;
            btnSend.BadgeAnimationEnabled = true;
            btnSend.BadgeAnimationSpeed = 0.15F;
            btnSend.BadgeColor = Color.Red;
            btnSend.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnSend.BadgePosition = SiticoneNetCoreUI.BadgePosition.TopRight;
            btnSend.BadgeTextColor = Color.White;
            btnSend.BadgeValue = 0;
            btnSend.BorderColor = Color.Transparent;
            btnSend.BorderThickness = 2;
            btnSend.CanBeep = true;
            btnSend.CanShake = true;
            btnSend.CornerRadiusBottomLeft = 17F;
            btnSend.CornerRadiusBottomRight = 17F;
            btnSend.CornerRadiusTopLeft = 17F;
            btnSend.CornerRadiusTopRight = 17F;
            btnSend.ImageDown = null;
            btnSend.ImageHover = null;
            btnSend.ImageNormal = (Image)resources.GetObject("btnSend.ImageNormal");
            btnSend.ImageSizing = SiticoneNetCoreUI.ImageSizingMode.Zoom;
            btnSend.IsReadOnly = false;
            btnSend.Location = new Point(846, 675);
            btnSend.MakeRadial = true;
            btnSend.Name = "btnSend";
            btnSend.PlaceholderImage = null;
            btnSend.RippleColor = Color.FromArgb(50, 0, 0, 0);
            btnSend.RippleEnabled = true;
            btnSend.Size = new Size(54, 37);
            btnSend.SpringEffectEnabled = true;
            btnSend.TabIndex = 2;
            btnSend.Text = "siticoneImageButton1";
            btnSend.TrackSystemTheme = false;
            btnSend.Click += btnSend_Click;
            // 
            // guna2ImageButton1
            // 
            guna2ImageButton1.BackColor = Color.Transparent;
            guna2ImageButton1.CheckedState.ImageSize = new Size(64, 64);
            guna2ImageButton1.HoverState.ImageSize = new Size(64, 64);
            guna2ImageButton1.Image = (Image)resources.GetObject("guna2ImageButton1.Image");
            guna2ImageButton1.ImageOffset = new Point(0, 0);
            guna2ImageButton1.ImageRotate = 0F;
            guna2ImageButton1.ImageSize = new Size(65, 60);
            guna2ImageButton1.Location = new Point(5, -1);
            guna2ImageButton1.Name = "guna2ImageButton1";
            guna2ImageButton1.PressedState.ImageSize = new Size(64, 64);
            guna2ImageButton1.ShadowDecoration.CustomizableEdges = customizableEdges3;
            guna2ImageButton1.Size = new Size(88, 77);
            guna2ImageButton1.TabIndex = 16;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("Tahoma", 16.2F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label1.ForeColor = Color.White;
            label1.Location = new Point(89, 21);
            label1.Name = "label1";
            label1.Size = new Size(281, 34);
            label1.TabIndex = 17;
            label1.Text = "Academic Network";
            // 
            // panel1
            // 
            panel1.BackColor = Color.FromArgb(30, 31, 34);
            panel1.Controls.Add(panelJoinGroup);
            panel1.Controls.Add(panelCreateGroup);
            panel1.Controls.Add(btnCreate);
            panel1.Controls.Add(dgvGroups);
            panel1.Controls.Add(siticoneButton2);
            panel1.Controls.Add(siticoneLabel1);
            panel1.Location = new Point(-2, 71);
            panel1.Name = "panel1";
            panel1.Size = new Size(275, 591);
            panel1.TabIndex = 0;
            panel1.Paint += panel1_Paint;
            // 
            // panelJoinGroup
            // 
            panelJoinGroup.Controls.Add(btnCancelJoin);
            panelJoinGroup.Controls.Add(btnConfirmJoin);
            panelJoinGroup.Controls.Add(dgvAvailableGroups);
            panelJoinGroup.Location = new Point(7, 97);
            panelJoinGroup.Margin = new Padding(3, 4, 3, 4);
            panelJoinGroup.Name = "panelJoinGroup";
            panelJoinGroup.Size = new Size(265, 492);
            panelJoinGroup.TabIndex = 7;
            panelJoinGroup.Visible = false;
            panelJoinGroup.Paint += panelJoinGroup_Paint;
            // 
            // btnCancelJoin
            // 
            btnCancelJoin.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            btnCancelJoin.AccessibleName = "Cancel";
            btnCancelJoin.AutoSizeBasedOnText = false;
            btnCancelJoin.BackColor = Color.Transparent;
            btnCancelJoin.BadgeBackColor = Color.Red;
            btnCancelJoin.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnCancelJoin.BadgeValue = 0;
            btnCancelJoin.BadgeValueForeColor = Color.White;
            btnCancelJoin.BorderColor = Color.Transparent;
            btnCancelJoin.BorderWidth = 2;
            btnCancelJoin.ButtonBackColor = Color.FromArgb(255, 128, 128);
            btnCancelJoin.ButtonImage = null;
            btnCancelJoin.CanBeep = true;
            btnCancelJoin.CanGlow = false;
            btnCancelJoin.CanShake = true;
            btnCancelJoin.ContextMenuStripEx = null;
            btnCancelJoin.CornerRadiusBottomLeft = 0;
            btnCancelJoin.CornerRadiusBottomRight = 0;
            btnCancelJoin.CornerRadiusTopLeft = 0;
            btnCancelJoin.CornerRadiusTopRight = 0;
            btnCancelJoin.CustomCursor = Cursors.Default;
            btnCancelJoin.DisabledTextColor = Color.FromArgb(150, 150, 150);
            btnCancelJoin.EnableLongPress = false;
            btnCancelJoin.EnablePressAnimation = true;
            btnCancelJoin.EnableRippleEffect = true;
            btnCancelJoin.EnableShadow = false;
            btnCancelJoin.EnableTextWrapping = false;
            btnCancelJoin.Font = new Font("Segoe UI", 9F);
            btnCancelJoin.GlowColor = Color.FromArgb(100, 255, 255, 255);
            btnCancelJoin.GlowIntensity = 100;
            btnCancelJoin.GlowRadius = 20F;
            btnCancelJoin.GradientBackground = false;
            btnCancelJoin.GradientColor = Color.FromArgb(114, 168, 255);
            btnCancelJoin.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            btnCancelJoin.HintText = null;
            btnCancelJoin.HoverBackColor = Color.FromArgb(114, 168, 255);
            btnCancelJoin.HoverFontStyle = FontStyle.Regular;
            btnCancelJoin.HoverTextColor = Color.White;
            btnCancelJoin.HoverTransitionDuration = 250;
            btnCancelJoin.ImageAlign = ContentAlignment.MiddleLeft;
            btnCancelJoin.ImagePadding = 5;
            btnCancelJoin.ImageSize = new Size(16, 16);
            btnCancelJoin.IsRadial = false;
            btnCancelJoin.IsReadOnly = false;
            btnCancelJoin.IsToggleButton = false;
            btnCancelJoin.IsToggled = false;
            btnCancelJoin.Location = new Point(51, 444);
            btnCancelJoin.LongPressDurationMS = 1000;
            btnCancelJoin.Margin = new Padding(3, 4, 3, 4);
            btnCancelJoin.Name = "btnCancelJoin";
            btnCancelJoin.NormalFontStyle = FontStyle.Regular;
            btnCancelJoin.ParticleColor = Color.FromArgb(200, 200, 200);
            btnCancelJoin.ParticleCount = 15;
            btnCancelJoin.PressAnimationScale = 0.97F;
            btnCancelJoin.PressedBackColor = Color.FromArgb(74, 128, 235);
            btnCancelJoin.PressedFontStyle = FontStyle.Regular;
            btnCancelJoin.PressTransitionDuration = 150;
            btnCancelJoin.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            btnCancelJoin.RippleColor = Color.FromArgb(255, 255, 255);
            btnCancelJoin.RippleOpacity = 0.3F;
            btnCancelJoin.RippleRadiusMultiplier = 0.6F;
            btnCancelJoin.ShadowBlur = 5;
            btnCancelJoin.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            btnCancelJoin.ShadowOffset = new Point(2, 2);
            btnCancelJoin.ShakeDuration = 500;
            btnCancelJoin.ShakeIntensity = 5;
            btnCancelJoin.Size = new Size(159, 37);
            btnCancelJoin.TabIndex = 4;
            btnCancelJoin.Text = "Cancel";
            btnCancelJoin.TextAlign = ContentAlignment.MiddleCenter;
            btnCancelJoin.TextColor = Color.White;
            btnCancelJoin.TooltipText = null;
            btnCancelJoin.UseAdvancedRendering = true;
            btnCancelJoin.UseParticles = false;
            btnCancelJoin.Click += btnCancelJoin_Click;
            // 
            // btnConfirmJoin
            // 
            btnConfirmJoin.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            btnConfirmJoin.AccessibleName = "Join Group";
            btnConfirmJoin.AutoSizeBasedOnText = false;
            btnConfirmJoin.BackColor = Color.Transparent;
            btnConfirmJoin.BadgeBackColor = Color.Red;
            btnConfirmJoin.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnConfirmJoin.BadgeValue = 0;
            btnConfirmJoin.BadgeValueForeColor = Color.White;
            btnConfirmJoin.BorderColor = Color.Transparent;
            btnConfirmJoin.BorderWidth = 2;
            btnConfirmJoin.ButtonBackColor = Color.Green;
            btnConfirmJoin.ButtonImage = null;
            btnConfirmJoin.CanBeep = true;
            btnConfirmJoin.CanGlow = false;
            btnConfirmJoin.CanShake = true;
            btnConfirmJoin.ContextMenuStripEx = null;
            btnConfirmJoin.CornerRadiusBottomLeft = 0;
            btnConfirmJoin.CornerRadiusBottomRight = 0;
            btnConfirmJoin.CornerRadiusTopLeft = 0;
            btnConfirmJoin.CornerRadiusTopRight = 0;
            btnConfirmJoin.CustomCursor = Cursors.Default;
            btnConfirmJoin.DisabledTextColor = Color.FromArgb(150, 150, 150);
            btnConfirmJoin.EnableLongPress = false;
            btnConfirmJoin.EnablePressAnimation = true;
            btnConfirmJoin.EnableRippleEffect = true;
            btnConfirmJoin.EnableShadow = false;
            btnConfirmJoin.EnableTextWrapping = false;
            btnConfirmJoin.Font = new Font("Segoe UI", 9F);
            btnConfirmJoin.GlowColor = Color.FromArgb(100, 255, 255, 255);
            btnConfirmJoin.GlowIntensity = 100;
            btnConfirmJoin.GlowRadius = 20F;
            btnConfirmJoin.GradientBackground = false;
            btnConfirmJoin.GradientColor = Color.FromArgb(114, 168, 255);
            btnConfirmJoin.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            btnConfirmJoin.HintText = null;
            btnConfirmJoin.HoverBackColor = Color.FromArgb(114, 168, 255);
            btnConfirmJoin.HoverFontStyle = FontStyle.Regular;
            btnConfirmJoin.HoverTextColor = Color.White;
            btnConfirmJoin.HoverTransitionDuration = 250;
            btnConfirmJoin.ImageAlign = ContentAlignment.MiddleLeft;
            btnConfirmJoin.ImagePadding = 5;
            btnConfirmJoin.ImageSize = new Size(16, 16);
            btnConfirmJoin.IsRadial = false;
            btnConfirmJoin.IsReadOnly = false;
            btnConfirmJoin.IsToggleButton = false;
            btnConfirmJoin.IsToggled = false;
            btnConfirmJoin.Location = new Point(51, 399);
            btnConfirmJoin.LongPressDurationMS = 1000;
            btnConfirmJoin.Margin = new Padding(3, 4, 3, 4);
            btnConfirmJoin.Name = "btnConfirmJoin";
            btnConfirmJoin.NormalFontStyle = FontStyle.Regular;
            btnConfirmJoin.ParticleColor = Color.FromArgb(200, 200, 200);
            btnConfirmJoin.ParticleCount = 15;
            btnConfirmJoin.PressAnimationScale = 0.97F;
            btnConfirmJoin.PressedBackColor = Color.FromArgb(74, 128, 235);
            btnConfirmJoin.PressedFontStyle = FontStyle.Regular;
            btnConfirmJoin.PressTransitionDuration = 150;
            btnConfirmJoin.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            btnConfirmJoin.RippleColor = Color.FromArgb(255, 255, 255);
            btnConfirmJoin.RippleOpacity = 0.3F;
            btnConfirmJoin.RippleRadiusMultiplier = 0.6F;
            btnConfirmJoin.ShadowBlur = 5;
            btnConfirmJoin.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            btnConfirmJoin.ShadowOffset = new Point(2, 2);
            btnConfirmJoin.ShakeDuration = 500;
            btnConfirmJoin.ShakeIntensity = 5;
            btnConfirmJoin.Size = new Size(159, 37);
            btnConfirmJoin.TabIndex = 3;
            btnConfirmJoin.Text = "Join Group";
            btnConfirmJoin.TextAlign = ContentAlignment.MiddleCenter;
            btnConfirmJoin.TextColor = Color.White;
            btnConfirmJoin.TooltipText = null;
            btnConfirmJoin.UseAdvancedRendering = true;
            btnConfirmJoin.UseParticles = false;
            btnConfirmJoin.Click += btnConfirmJoin_Click;
            // 
            // dgvAvailableGroups
            // 
            dgvAvailableGroups.AllowUserToAddRows = false;
            dgvAvailableGroups.AllowUserToDeleteRows = false;
            dgvAvailableGroups.AllowUserToResizeColumns = false;
            dgvAvailableGroups.AllowUserToResizeRows = false;
            dgvAvailableGroups.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvAvailableGroups.BackgroundColor = Color.FromArgb(30, 31, 34);
            dgvAvailableGroups.CellBorderStyle = DataGridViewCellBorderStyle.None;
            dgvAvailableGroups.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvAvailableGroups.ColumnHeadersVisible = false;
            dgvAvailableGroups.Location = new Point(23, 16);
            dgvAvailableGroups.Margin = new Padding(3, 4, 3, 4);
            dgvAvailableGroups.Name = "dgvAvailableGroups";
            dgvAvailableGroups.ReadOnly = true;
            dgvAvailableGroups.RowHeadersVisible = false;
            dgvAvailableGroups.RowHeadersWidth = 51;
            dgvAvailableGroups.SelectionMode = DataGridViewSelectionMode.CellSelect;
            dgvAvailableGroups.ShowEditingIcon = false;
            dgvAvailableGroups.Size = new Size(206, 375);
            dgvAvailableGroups.TabIndex = 0;
            dgvAvailableGroups.CellClick += dgvAvailableGroups_CellClick_1;
            // 
            // panelCreateGroup
            // 
            panelCreateGroup.Controls.Add(btnCancelCreateGroup);
            panelCreateGroup.Controls.Add(btnConfirmCreateGroup);
            panelCreateGroup.Controls.Add(txtGroupName);
            panelCreateGroup.Location = new Point(5, 299);
            panelCreateGroup.Margin = new Padding(3, 4, 3, 4);
            panelCreateGroup.Name = "panelCreateGroup";
            panelCreateGroup.Size = new Size(267, 179);
            panelCreateGroup.TabIndex = 6;
            panelCreateGroup.Visible = false;
            // 
            // btnCancelCreateGroup
            // 
            btnCancelCreateGroup.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            btnCancelCreateGroup.AccessibleName = "Cancel";
            btnCancelCreateGroup.AutoSizeBasedOnText = false;
            btnCancelCreateGroup.BackColor = Color.Transparent;
            btnCancelCreateGroup.BadgeBackColor = Color.Red;
            btnCancelCreateGroup.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnCancelCreateGroup.BadgeValue = 0;
            btnCancelCreateGroup.BadgeValueForeColor = Color.White;
            btnCancelCreateGroup.BorderColor = Color.Transparent;
            btnCancelCreateGroup.BorderWidth = 2;
            btnCancelCreateGroup.ButtonBackColor = Color.FromArgb(255, 128, 128);
            btnCancelCreateGroup.ButtonImage = null;
            btnCancelCreateGroup.CanBeep = true;
            btnCancelCreateGroup.CanGlow = false;
            btnCancelCreateGroup.CanShake = true;
            btnCancelCreateGroup.ContextMenuStripEx = null;
            btnCancelCreateGroup.CornerRadiusBottomLeft = 0;
            btnCancelCreateGroup.CornerRadiusBottomRight = 0;
            btnCancelCreateGroup.CornerRadiusTopLeft = 0;
            btnCancelCreateGroup.CornerRadiusTopRight = 0;
            btnCancelCreateGroup.CustomCursor = Cursors.Default;
            btnCancelCreateGroup.DisabledTextColor = Color.FromArgb(150, 150, 150);
            btnCancelCreateGroup.EnableLongPress = false;
            btnCancelCreateGroup.EnablePressAnimation = true;
            btnCancelCreateGroup.EnableRippleEffect = true;
            btnCancelCreateGroup.EnableShadow = false;
            btnCancelCreateGroup.EnableTextWrapping = false;
            btnCancelCreateGroup.Font = new Font("Segoe UI", 9F);
            btnCancelCreateGroup.GlowColor = Color.FromArgb(100, 255, 255, 255);
            btnCancelCreateGroup.GlowIntensity = 100;
            btnCancelCreateGroup.GlowRadius = 20F;
            btnCancelCreateGroup.GradientBackground = false;
            btnCancelCreateGroup.GradientColor = Color.FromArgb(114, 168, 255);
            btnCancelCreateGroup.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            btnCancelCreateGroup.HintText = null;
            btnCancelCreateGroup.HoverBackColor = Color.FromArgb(114, 168, 255);
            btnCancelCreateGroup.HoverFontStyle = FontStyle.Regular;
            btnCancelCreateGroup.HoverTextColor = Color.White;
            btnCancelCreateGroup.HoverTransitionDuration = 250;
            btnCancelCreateGroup.ImageAlign = ContentAlignment.MiddleLeft;
            btnCancelCreateGroup.ImagePadding = 5;
            btnCancelCreateGroup.ImageSize = new Size(16, 16);
            btnCancelCreateGroup.IsRadial = false;
            btnCancelCreateGroup.IsReadOnly = false;
            btnCancelCreateGroup.IsToggleButton = false;
            btnCancelCreateGroup.IsToggled = false;
            btnCancelCreateGroup.Location = new Point(54, 117);
            btnCancelCreateGroup.LongPressDurationMS = 1000;
            btnCancelCreateGroup.Margin = new Padding(3, 4, 3, 4);
            btnCancelCreateGroup.Name = "btnCancelCreateGroup";
            btnCancelCreateGroup.NormalFontStyle = FontStyle.Regular;
            btnCancelCreateGroup.ParticleColor = Color.FromArgb(200, 200, 200);
            btnCancelCreateGroup.ParticleCount = 15;
            btnCancelCreateGroup.PressAnimationScale = 0.97F;
            btnCancelCreateGroup.PressedBackColor = Color.FromArgb(74, 128, 235);
            btnCancelCreateGroup.PressedFontStyle = FontStyle.Regular;
            btnCancelCreateGroup.PressTransitionDuration = 150;
            btnCancelCreateGroup.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            btnCancelCreateGroup.RippleColor = Color.FromArgb(255, 255, 255);
            btnCancelCreateGroup.RippleOpacity = 0.3F;
            btnCancelCreateGroup.RippleRadiusMultiplier = 0.6F;
            btnCancelCreateGroup.ShadowBlur = 5;
            btnCancelCreateGroup.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            btnCancelCreateGroup.ShadowOffset = new Point(2, 2);
            btnCancelCreateGroup.ShakeDuration = 500;
            btnCancelCreateGroup.ShakeIntensity = 5;
            btnCancelCreateGroup.Size = new Size(159, 37);
            btnCancelCreateGroup.TabIndex = 3;
            btnCancelCreateGroup.Text = "Cancel";
            btnCancelCreateGroup.TextAlign = ContentAlignment.MiddleCenter;
            btnCancelCreateGroup.TextColor = Color.White;
            btnCancelCreateGroup.TooltipText = null;
            btnCancelCreateGroup.UseAdvancedRendering = true;
            btnCancelCreateGroup.UseParticles = false;
            btnCancelCreateGroup.Click += btnCancelCreateGroup_Click;
            // 
            // btnConfirmCreateGroup
            // 
            btnConfirmCreateGroup.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            btnConfirmCreateGroup.AccessibleName = "Create Group";
            btnConfirmCreateGroup.AutoSizeBasedOnText = false;
            btnConfirmCreateGroup.BackColor = Color.Transparent;
            btnConfirmCreateGroup.BadgeBackColor = Color.Red;
            btnConfirmCreateGroup.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnConfirmCreateGroup.BadgeValue = 0;
            btnConfirmCreateGroup.BadgeValueForeColor = Color.White;
            btnConfirmCreateGroup.BorderColor = Color.Transparent;
            btnConfirmCreateGroup.BorderWidth = 2;
            btnConfirmCreateGroup.ButtonBackColor = Color.Green;
            btnConfirmCreateGroup.ButtonImage = null;
            btnConfirmCreateGroup.CanBeep = true;
            btnConfirmCreateGroup.CanGlow = false;
            btnConfirmCreateGroup.CanShake = true;
            btnConfirmCreateGroup.ContextMenuStripEx = null;
            btnConfirmCreateGroup.CornerRadiusBottomLeft = 0;
            btnConfirmCreateGroup.CornerRadiusBottomRight = 0;
            btnConfirmCreateGroup.CornerRadiusTopLeft = 0;
            btnConfirmCreateGroup.CornerRadiusTopRight = 0;
            btnConfirmCreateGroup.CustomCursor = Cursors.Default;
            btnConfirmCreateGroup.DisabledTextColor = Color.FromArgb(150, 150, 150);
            btnConfirmCreateGroup.EnableLongPress = false;
            btnConfirmCreateGroup.EnablePressAnimation = true;
            btnConfirmCreateGroup.EnableRippleEffect = true;
            btnConfirmCreateGroup.EnableShadow = false;
            btnConfirmCreateGroup.EnableTextWrapping = false;
            btnConfirmCreateGroup.Font = new Font("Segoe UI", 9F);
            btnConfirmCreateGroup.GlowColor = Color.FromArgb(100, 255, 255, 255);
            btnConfirmCreateGroup.GlowIntensity = 100;
            btnConfirmCreateGroup.GlowRadius = 20F;
            btnConfirmCreateGroup.GradientBackground = false;
            btnConfirmCreateGroup.GradientColor = Color.FromArgb(114, 168, 255);
            btnConfirmCreateGroup.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            btnConfirmCreateGroup.HintText = null;
            btnConfirmCreateGroup.HoverBackColor = Color.FromArgb(114, 168, 255);
            btnConfirmCreateGroup.HoverFontStyle = FontStyle.Regular;
            btnConfirmCreateGroup.HoverTextColor = Color.White;
            btnConfirmCreateGroup.HoverTransitionDuration = 250;
            btnConfirmCreateGroup.ImageAlign = ContentAlignment.MiddleLeft;
            btnConfirmCreateGroup.ImagePadding = 5;
            btnConfirmCreateGroup.ImageSize = new Size(16, 16);
            btnConfirmCreateGroup.IsRadial = false;
            btnConfirmCreateGroup.IsReadOnly = false;
            btnConfirmCreateGroup.IsToggleButton = false;
            btnConfirmCreateGroup.IsToggled = false;
            btnConfirmCreateGroup.Location = new Point(54, 72);
            btnConfirmCreateGroup.LongPressDurationMS = 1000;
            btnConfirmCreateGroup.Margin = new Padding(3, 4, 3, 4);
            btnConfirmCreateGroup.Name = "btnConfirmCreateGroup";
            btnConfirmCreateGroup.NormalFontStyle = FontStyle.Regular;
            btnConfirmCreateGroup.ParticleColor = Color.FromArgb(200, 200, 200);
            btnConfirmCreateGroup.ParticleCount = 15;
            btnConfirmCreateGroup.PressAnimationScale = 0.97F;
            btnConfirmCreateGroup.PressedBackColor = Color.FromArgb(74, 128, 235);
            btnConfirmCreateGroup.PressedFontStyle = FontStyle.Regular;
            btnConfirmCreateGroup.PressTransitionDuration = 150;
            btnConfirmCreateGroup.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            btnConfirmCreateGroup.RippleColor = Color.FromArgb(255, 255, 255);
            btnConfirmCreateGroup.RippleOpacity = 0.3F;
            btnConfirmCreateGroup.RippleRadiusMultiplier = 0.6F;
            btnConfirmCreateGroup.ShadowBlur = 5;
            btnConfirmCreateGroup.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            btnConfirmCreateGroup.ShadowOffset = new Point(2, 2);
            btnConfirmCreateGroup.ShakeDuration = 500;
            btnConfirmCreateGroup.ShakeIntensity = 5;
            btnConfirmCreateGroup.Size = new Size(159, 37);
            btnConfirmCreateGroup.TabIndex = 2;
            btnConfirmCreateGroup.Text = "Create Group";
            btnConfirmCreateGroup.TextAlign = ContentAlignment.MiddleCenter;
            btnConfirmCreateGroup.TextColor = Color.White;
            btnConfirmCreateGroup.TooltipText = null;
            btnConfirmCreateGroup.UseAdvancedRendering = true;
            btnConfirmCreateGroup.UseParticles = false;
            btnConfirmCreateGroup.Click += btnConfirmCreateGroup_Click;
            // 
            // txtGroupName
            // 
            txtGroupName.AccessibleDescription = "A customizable text input field.";
            txtGroupName.AccessibleName = "Text Box";
            txtGroupName.AccessibleRole = AccessibleRole.Text;
            txtGroupName.BackColor = Color.Transparent;
            txtGroupName.BlinkCount = 3;
            txtGroupName.BlinkShadow = false;
            txtGroupName.BorderColor1 = Color.LightSlateGray;
            txtGroupName.BorderColor2 = Color.LightSlateGray;
            txtGroupName.BorderFocusColor1 = Color.FromArgb(77, 77, 255);
            txtGroupName.BorderFocusColor2 = Color.FromArgb(77, 77, 255);
            txtGroupName.CanShake = true;
            txtGroupName.ContinuousBlink = false;
            txtGroupName.CursorBlinkRate = 500;
            txtGroupName.CursorColor = Color.Black;
            txtGroupName.CursorHeight = 26;
            txtGroupName.CursorOffset = 0;
            txtGroupName.CursorStyle = SiticoneNetCoreUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            txtGroupName.CursorWidth = 1;
            txtGroupName.DisabledBackColor = Color.WhiteSmoke;
            txtGroupName.DisabledBorderColor = Color.LightGray;
            txtGroupName.DisabledTextColor = Color.Gray;
            txtGroupName.EnableDropShadow = false;
            txtGroupName.FillColor1 = Color.White;
            txtGroupName.FillColor2 = Color.White;
            txtGroupName.Font = new Font("Segoe UI", 9.5F);
            txtGroupName.ForeColor = Color.DimGray;
            txtGroupName.HoverBorderColor1 = Color.Gray;
            txtGroupName.HoverBorderColor2 = Color.Gray;
            txtGroupName.IsEnabled = true;
            txtGroupName.Location = new Point(16, 11);
            txtGroupName.Margin = new Padding(3, 4, 3, 4);
            txtGroupName.Name = "txtGroupName";
            txtGroupName.PlaceholderColor = Color.Gray;
            txtGroupName.PlaceholderText = "Enter Group Name...";
            txtGroupName.ReadOnlyBorderColor1 = Color.LightGray;
            txtGroupName.ReadOnlyBorderColor2 = Color.LightGray;
            txtGroupName.ReadOnlyFillColor1 = Color.WhiteSmoke;
            txtGroupName.ReadOnlyFillColor2 = Color.WhiteSmoke;
            txtGroupName.ReadOnlyPlaceholderColor = Color.DarkGray;
            txtGroupName.SelectionBackColor = Color.FromArgb(77, 77, 255);
            txtGroupName.ShadowAnimationDuration = 1;
            txtGroupName.ShadowBlur = 10;
            txtGroupName.ShadowColor = Color.FromArgb(15, 0, 0, 0);
            txtGroupName.Size = new Size(241, 53);
            txtGroupName.SolidBorderColor = Color.LightSlateGray;
            txtGroupName.SolidBorderFocusColor = Color.FromArgb(77, 77, 255);
            txtGroupName.SolidBorderHoverColor = Color.Gray;
            txtGroupName.SolidFillColor = Color.White;
            txtGroupName.TabIndex = 0;
            txtGroupName.TextPadding = new Padding(16, 0, 6, 0);
            txtGroupName.ValidationErrorMessage = "Invalid input.";
            txtGroupName.ValidationFunction = null;
            // 
            // btnCreate
            // 
            btnCreate.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            btnCreate.AccessibleName = "Create Group";
            btnCreate.AutoSizeBasedOnText = false;
            btnCreate.BackColor = Color.Transparent;
            btnCreate.BadgeBackColor = Color.Red;
            btnCreate.BadgeFont = new Font("Tahoma", 7.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btnCreate.BadgeValue = 0;
            btnCreate.BadgeValueForeColor = Color.White;
            btnCreate.BorderColor = Color.Transparent;
            btnCreate.BorderWidth = 2;
            btnCreate.ButtonBackColor = Color.Transparent;
            btnCreate.ButtonImage = Properties.Resources.icons8_join_100__1_;
            btnCreate.CanBeep = true;
            btnCreate.CanGlow = false;
            btnCreate.CanShake = true;
            btnCreate.ContextMenuStripEx = null;
            btnCreate.CornerRadiusBottomLeft = 0;
            btnCreate.CornerRadiusBottomRight = 0;
            btnCreate.CornerRadiusTopLeft = 0;
            btnCreate.CornerRadiusTopRight = 0;
            btnCreate.CustomCursor = Cursors.Default;
            btnCreate.DisabledTextColor = Color.FromArgb(150, 150, 150);
            btnCreate.EnableLongPress = false;
            btnCreate.EnablePressAnimation = true;
            btnCreate.EnableRippleEffect = true;
            btnCreate.EnableShadow = false;
            btnCreate.EnableTextWrapping = false;
            btnCreate.Font = new Font("Tahoma", 9F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btnCreate.GlowColor = Color.FromArgb(100, 255, 255, 255);
            btnCreate.GlowIntensity = 100;
            btnCreate.GlowRadius = 20F;
            btnCreate.GradientBackground = false;
            btnCreate.GradientColor = Color.FromArgb(114, 168, 255);
            btnCreate.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            btnCreate.HintText = null;
            btnCreate.HoverBackColor = Color.FromArgb(114, 168, 255);
            btnCreate.HoverFontStyle = FontStyle.Regular;
            btnCreate.HoverTextColor = Color.White;
            btnCreate.HoverTransitionDuration = 250;
            btnCreate.ImageAlign = ContentAlignment.MiddleLeft;
            btnCreate.ImagePadding = 5;
            btnCreate.ImageSize = new Size(30, 30);
            btnCreate.IsRadial = false;
            btnCreate.IsReadOnly = false;
            btnCreate.IsToggleButton = false;
            btnCreate.IsToggled = false;
            btnCreate.Location = new Point(58, 484);
            btnCreate.LongPressDurationMS = 1000;
            btnCreate.Name = "btnCreate";
            btnCreate.NormalFontStyle = FontStyle.Regular;
            btnCreate.ParticleColor = Color.FromArgb(200, 200, 200);
            btnCreate.ParticleCount = 15;
            btnCreate.PressAnimationScale = 0.97F;
            btnCreate.PressedBackColor = Color.FromArgb(74, 128, 235);
            btnCreate.PressedFontStyle = FontStyle.Regular;
            btnCreate.PressTransitionDuration = 150;
            btnCreate.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            btnCreate.RippleColor = Color.FromArgb(255, 255, 255);
            btnCreate.RippleOpacity = 0.3F;
            btnCreate.RippleRadiusMultiplier = 0.6F;
            btnCreate.ShadowBlur = 5;
            btnCreate.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            btnCreate.ShadowOffset = new Point(2, 2);
            btnCreate.ShakeDuration = 500;
            btnCreate.ShakeIntensity = 5;
            btnCreate.Size = new Size(152, 36);
            btnCreate.TabIndex = 5;
            btnCreate.Text = "Create Group";
            btnCreate.TextAlign = ContentAlignment.MiddleLeft;
            btnCreate.TextColor = Color.White;
            btnCreate.TooltipText = null;
            btnCreate.UseAdvancedRendering = true;
            btnCreate.UseParticles = false;
            btnCreate.Click += btnCreate_Click;
            // 
            // dgvGroups
            // 
            dgvGroups.AllowUserToAddRows = false;
            dgvGroups.AllowUserToDeleteRows = false;
            dgvGroups.AllowUserToResizeColumns = false;
            dgvGroups.AllowUserToResizeRows = false;
            dgvGroups.BackgroundColor = Color.FromArgb(30, 31, 34);
            dgvGroups.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvGroups.ColumnHeadersVisible = false;
            dgvGroups.Location = new Point(7, 97);
            dgvGroups.Margin = new Padding(3, 4, 3, 4);
            dgvGroups.Name = "dgvGroups";
            dgvGroups.ReadOnly = true;
            dgvGroups.RowHeadersVisible = false;
            dgvGroups.RowHeadersWidth = 51;
            dgvGroups.Size = new Size(257, 377);
            dgvGroups.TabIndex = 4;
            dgvGroups.CellClick += dgvGroups_CellClick;
            dgvGroups.CellContentClick += dgvGroups_CellContentClick;
            // 
            // siticoneButton2
            // 
            siticoneButton2.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButton2.AccessibleName = "Join Group";
            siticoneButton2.AutoSizeBasedOnText = false;
            siticoneButton2.BackColor = Color.Transparent;
            siticoneButton2.BadgeBackColor = Color.Red;
            siticoneButton2.BadgeFont = new Font("Tahoma", 7.8F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton2.BadgeValue = 0;
            siticoneButton2.BadgeValueForeColor = Color.White;
            siticoneButton2.BorderColor = Color.Transparent;
            siticoneButton2.BorderWidth = 2;
            siticoneButton2.ButtonBackColor = Color.Transparent;
            siticoneButton2.ButtonImage = Properties.Resources.icons8_join_100__1_;
            siticoneButton2.CanBeep = true;
            siticoneButton2.CanGlow = false;
            siticoneButton2.CanShake = true;
            siticoneButton2.ContextMenuStripEx = null;
            siticoneButton2.CornerRadiusBottomLeft = 0;
            siticoneButton2.CornerRadiusBottomRight = 0;
            siticoneButton2.CornerRadiusTopLeft = 0;
            siticoneButton2.CornerRadiusTopRight = 0;
            siticoneButton2.CustomCursor = Cursors.Default;
            siticoneButton2.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButton2.EnableLongPress = false;
            siticoneButton2.EnablePressAnimation = true;
            siticoneButton2.EnableRippleEffect = true;
            siticoneButton2.EnableShadow = false;
            siticoneButton2.EnableTextWrapping = false;
            siticoneButton2.Font = new Font("Tahoma", 9F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneButton2.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButton2.GlowIntensity = 100;
            siticoneButton2.GlowRadius = 20F;
            siticoneButton2.GradientBackground = false;
            siticoneButton2.GradientColor = Color.FromArgb(114, 168, 255);
            siticoneButton2.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButton2.HintText = null;
            siticoneButton2.HoverBackColor = Color.FromArgb(114, 168, 255);
            siticoneButton2.HoverFontStyle = FontStyle.Regular;
            siticoneButton2.HoverTextColor = Color.White;
            siticoneButton2.HoverTransitionDuration = 250;
            siticoneButton2.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButton2.ImagePadding = 5;
            siticoneButton2.ImageSize = new Size(30, 30);
            siticoneButton2.IsRadial = false;
            siticoneButton2.IsReadOnly = false;
            siticoneButton2.IsToggleButton = false;
            siticoneButton2.IsToggled = false;
            siticoneButton2.Location = new Point(58, 525);
            siticoneButton2.LongPressDurationMS = 1000;
            siticoneButton2.Name = "siticoneButton2";
            siticoneButton2.NormalFontStyle = FontStyle.Regular;
            siticoneButton2.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButton2.ParticleCount = 15;
            siticoneButton2.PressAnimationScale = 0.97F;
            siticoneButton2.PressedBackColor = Color.FromArgb(74, 128, 235);
            siticoneButton2.PressedFontStyle = FontStyle.Regular;
            siticoneButton2.PressTransitionDuration = 150;
            siticoneButton2.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButton2.RippleColor = Color.FromArgb(255, 255, 255);
            siticoneButton2.RippleOpacity = 0.3F;
            siticoneButton2.RippleRadiusMultiplier = 0.6F;
            siticoneButton2.ShadowBlur = 5;
            siticoneButton2.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            siticoneButton2.ShadowOffset = new Point(2, 2);
            siticoneButton2.ShakeDuration = 500;
            siticoneButton2.ShakeIntensity = 5;
            siticoneButton2.Size = new Size(152, 36);
            siticoneButton2.TabIndex = 3;
            siticoneButton2.Text = "Join Group";
            siticoneButton2.TextAlign = ContentAlignment.MiddleLeft;
            siticoneButton2.TextColor = Color.White;
            siticoneButton2.TooltipText = null;
            siticoneButton2.UseAdvancedRendering = true;
            siticoneButton2.UseParticles = false;
            siticoneButton2.Click += siticoneButton2_Click_1;
            // 
            // siticoneLabel1
            // 
            siticoneLabel1.BackColor = Color.Transparent;
            siticoneLabel1.Font = new Font("Segoe UI", 10F);
            siticoneLabel1.ForeColor = Color.White;
            siticoneLabel1.Location = new Point(43, 58);
            siticoneLabel1.Name = "siticoneLabel1";
            siticoneLabel1.Size = new Size(125, 29);
            siticoneLabel1.TabIndex = 1;
            siticoneLabel1.Text = "My Groups";
            // 
            // panel2
            // 
            panel2.BackColor = Color.DarkSlateBlue;
            panel2.Controls.Add(lblSelectedGroupID);
            panel2.Controls.Add(siticoneCloseButton1);
            panel2.Controls.Add(guna2ImageButton1);
            panel2.Controls.Add(label1);
            panel2.Location = new Point(-2, 3);
            panel2.Name = "panel2";
            panel2.Size = new Size(1025, 72);
            panel2.TabIndex = 3;
            // 
            // lblSelectedGroupID
            // 
            lblSelectedGroupID.AutoSize = true;
            lblSelectedGroupID.Location = new Point(785, 15);
            lblSelectedGroupID.Name = "lblSelectedGroupID";
            lblSelectedGroupID.Size = new Size(50, 20);
            lblSelectedGroupID.TabIndex = 19;
            lblSelectedGroupID.Text = "label2";
            lblSelectedGroupID.Visible = false;
            // 
            // siticoneCloseButton1
            // 
            siticoneCloseButton1.BackColor = Color.Transparent;
            siticoneCloseButton1.CountdownFont = new Font("Segoe UI", 9F);
            siticoneCloseButton1.Cursor = Cursors.Default;
            siticoneCloseButton1.EnableSound = false;
            siticoneCloseButton1.IconColor = Color.White;
            siticoneCloseButton1.Location = new Point(978, 13);
            siticoneCloseButton1.Name = "siticoneCloseButton1";
            siticoneCloseButton1.Size = new Size(55, 55);
            siticoneCloseButton1.TabIndex = 18;
            siticoneCloseButton1.Text = "siticoneCloseButton1";
            siticoneCloseButton1.TooltipText = "Close button";
            // 
            // panel3
            // 
            panel3.BackColor = SystemColors.ControlDarkDark;
            panel3.Controls.Add(siticoneImageButton3);
            panel3.Controls.Add(lblUsernameDisplay);
            panel3.Controls.Add(siticoneImageButton2);
            panel3.Location = new Point(2, 661);
            panel3.Name = "panel3";
            panel3.Size = new Size(271, 135);
            panel3.TabIndex = 2;
            panel3.Paint += panel3_Paint;
            // 
            // siticoneImageButton3
            // 
            siticoneImageButton3.AnimationSpeed = 0.15F;
            siticoneImageButton3.BackColor = Color.Transparent;
            siticoneImageButton3.BackgroundFillColor = Color.Transparent;
            siticoneImageButton3.BadgeAnimationEnabled = true;
            siticoneImageButton3.BadgeAnimationSpeed = 0.15F;
            siticoneImageButton3.BadgeColor = Color.Red;
            siticoneImageButton3.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneImageButton3.BadgePosition = SiticoneNetCoreUI.BadgePosition.TopRight;
            siticoneImageButton3.BadgeTextColor = Color.White;
            siticoneImageButton3.BadgeValue = 0;
            siticoneImageButton3.BorderColor = Color.Transparent;
            siticoneImageButton3.BorderThickness = 2;
            siticoneImageButton3.CanBeep = true;
            siticoneImageButton3.CanShake = true;
            siticoneImageButton3.CornerRadiusBottomLeft = 25F;
            siticoneImageButton3.CornerRadiusBottomRight = 25F;
            siticoneImageButton3.CornerRadiusTopLeft = 25F;
            siticoneImageButton3.CornerRadiusTopRight = 25F;
            siticoneImageButton3.ImageDown = null;
            siticoneImageButton3.ImageHover = null;
            siticoneImageButton3.ImageNormal = Properties.Resources.icons8_user_100;
            siticoneImageButton3.ImageSizing = SiticoneNetCoreUI.ImageSizingMode.Zoom;
            siticoneImageButton3.IsReadOnly = false;
            siticoneImageButton3.Location = new Point(16, 3);
            siticoneImageButton3.MakeRadial = true;
            siticoneImageButton3.Name = "siticoneImageButton3";
            siticoneImageButton3.PlaceholderImage = null;
            siticoneImageButton3.RippleColor = Color.FromArgb(50, 0, 0, 0);
            siticoneImageButton3.RippleEnabled = true;
            siticoneImageButton3.Size = new Size(53, 53);
            siticoneImageButton3.SpringEffectEnabled = true;
            siticoneImageButton3.TabIndex = 4;
            siticoneImageButton3.Text = "siticoneImageButton3";
            siticoneImageButton3.TrackSystemTheme = false;
            // 
            // lblUsernameDisplay
            // 
            lblUsernameDisplay.AutoSize = true;
            lblUsernameDisplay.Font = new Font("Segoe UI", 13.8F, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblUsernameDisplay.Location = new Point(65, 17);
            lblUsernameDisplay.Name = "lblUsernameDisplay";
            lblUsernameDisplay.Size = new Size(60, 31);
            lblUsernameDisplay.TabIndex = 5;
            lblUsernameDisplay.Text = "User";
            // 
            // siticoneImageButton2
            // 
            siticoneImageButton2.AnimationSpeed = 0.15F;
            siticoneImageButton2.BackColor = Color.Transparent;
            siticoneImageButton2.BackgroundFillColor = Color.Transparent;
            siticoneImageButton2.BadgeAnimationEnabled = true;
            siticoneImageButton2.BadgeAnimationSpeed = 0.15F;
            siticoneImageButton2.BadgeColor = Color.Red;
            siticoneImageButton2.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneImageButton2.BadgePosition = SiticoneNetCoreUI.BadgePosition.TopRight;
            siticoneImageButton2.BadgeTextColor = Color.White;
            siticoneImageButton2.BadgeValue = 0;
            siticoneImageButton2.BorderColor = Color.Transparent;
            siticoneImageButton2.BorderThickness = 2;
            siticoneImageButton2.CanBeep = true;
            siticoneImageButton2.CanShake = true;
            siticoneImageButton2.CornerRadiusBottomLeft = 15F;
            siticoneImageButton2.CornerRadiusBottomRight = 15F;
            siticoneImageButton2.CornerRadiusTopLeft = 15F;
            siticoneImageButton2.CornerRadiusTopRight = 15F;
            siticoneImageButton2.ImageDown = null;
            siticoneImageButton2.ImageHover = null;
            siticoneImageButton2.ImageNormal = Properties.Resources.icons8_settings_100__1_;
            siticoneImageButton2.ImageSizing = SiticoneNetCoreUI.ImageSizingMode.Stretch;
            siticoneImageButton2.IsReadOnly = false;
            siticoneImageButton2.Location = new Point(217, 17);
            siticoneImageButton2.MakeRadial = true;
            siticoneImageButton2.Name = "siticoneImageButton2";
            siticoneImageButton2.PlaceholderImage = null;
            siticoneImageButton2.RippleColor = Color.FromArgb(50, 0, 0, 0);
            siticoneImageButton2.RippleEnabled = true;
            siticoneImageButton2.Size = new Size(33, 35);
            siticoneImageButton2.SpringEffectEnabled = true;
            siticoneImageButton2.TabIndex = 4;
            siticoneImageButton2.Text = "siticoneImageButton2";
            siticoneImageButton2.TrackSystemTheme = false;
            siticoneImageButton2.Click += siticoneImageButton2_Click;
            // 
            // rightBtn
            // 
            rightBtn.AllowDynamicSwitch = true;
            rightBtn.BackColor = Color.Transparent;
            rightBtn.BorderRadius = 8;
            rightBtn.BounceDuration = 500;
            rightBtn.BounceStrength = 0.3F;
            rightBtn.CanBeep = true;
            rightBtn.CanShake = true;
            rightBtn.EnableParticles = true;
            rightBtn.EnablePulseEffect = true;
            rightBtn.EnableRippleEffect = true;
            rightBtn.EnableShadow = true;
            rightBtn.ForeColor = Color.White;
            rightBtn.HoverAnimationSpeed = 200;
            rightBtn.HoverColor = Color.FromArgb(240, 240, 240);
            rightBtn.HoverOpacity = 150;
            rightBtn.IconSize = 24F;
            rightBtn.IconStrokeWidth = 2F;
            rightBtn.InteractiveBounce = false;
            rightBtn.IsOpened = false;
            rightBtn.IsReadOnly = false;
            rightBtn.Location = new Point(693, 11);
            rightBtn.MenuLineColor = Color.White;
            rightBtn.MenuLineHeight = 2F;
            rightBtn.MenuLineSpacing = 6F;
            rightBtn.MenuLineWidth = 20F;
            rightBtn.Name = "rightBtn";
            rightBtn.ParticleColor = Color.FromArgb(100, 149, 237);
            rightBtn.ParticleCount = 20;
            rightBtn.ParticleSpeed = 3F;
            rightBtn.PressAnimationSpeed = 100;
            rightBtn.PressColor = Color.FromArgb(240, 240, 240);
            rightBtn.PressDepthOffset = 2;
            rightBtn.PressShadowColor = Color.FromArgb(240, 240, 240);
            rightBtn.ShadowColor = Color.Transparent;
            rightBtn.ShadowDepth = 3;
            rightBtn.Size = new Size(50, 51);
            rightBtn.TabIndex = 4;
            rightBtn.Text = "siticoneMenuButton1";
            rightBtn.XIconColor = Color.Black;
            rightBtn.XIconSize = 20F;
            rightBtn.XIconThickness = 2F;
            rightBtn.Click += rightBtn_Click;
            rightBtn.MouseClick += rightBtn_MouseClick;
            // 
            // panelMembers
            // 
            panelMembers.BackColor = Color.FromArgb(30, 31, 34);
            panelMembers.Controls.Add(btnKickMember);
            panelMembers.Controls.Add(lstGroupMembers);
            panelMembers.Controls.Add(dgvMembers);
            panelMembers.Controls.Add(label3);
            panelMembers.Location = new Point(880, 137);
            panelMembers.Name = "panelMembers";
            panelMembers.Size = new Size(139, 509);
            panelMembers.TabIndex = 5;
            panelMembers.Visible = false;
            // 
            // btnKickMember
            // 
            btnKickMember.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            btnKickMember.AccessibleName = "Kick Member";
            btnKickMember.AutoSizeBasedOnText = false;
            btnKickMember.BackColor = Color.Transparent;
            btnKickMember.BadgeBackColor = Color.Red;
            btnKickMember.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnKickMember.BadgeValue = 0;
            btnKickMember.BadgeValueForeColor = Color.White;
            btnKickMember.BorderColor = Color.Transparent;
            btnKickMember.BorderWidth = 2;
            btnKickMember.ButtonBackColor = Color.Maroon;
            btnKickMember.ButtonImage = null;
            btnKickMember.CanBeep = true;
            btnKickMember.CanGlow = false;
            btnKickMember.CanShake = true;
            btnKickMember.ContextMenuStripEx = null;
            btnKickMember.CornerRadiusBottomLeft = 0;
            btnKickMember.CornerRadiusBottomRight = 0;
            btnKickMember.CornerRadiusTopLeft = 0;
            btnKickMember.CornerRadiusTopRight = 0;
            btnKickMember.CustomCursor = Cursors.Default;
            btnKickMember.DisabledTextColor = Color.FromArgb(150, 150, 150);
            btnKickMember.EnableLongPress = false;
            btnKickMember.EnablePressAnimation = true;
            btnKickMember.EnableRippleEffect = true;
            btnKickMember.EnableShadow = false;
            btnKickMember.EnableTextWrapping = false;
            btnKickMember.Font = new Font("Segoe UI", 9F);
            btnKickMember.GlowColor = Color.FromArgb(100, 255, 255, 255);
            btnKickMember.GlowIntensity = 100;
            btnKickMember.GlowRadius = 20F;
            btnKickMember.GradientBackground = false;
            btnKickMember.GradientColor = Color.FromArgb(114, 168, 255);
            btnKickMember.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            btnKickMember.HintText = null;
            btnKickMember.HoverBackColor = Color.FromArgb(114, 168, 255);
            btnKickMember.HoverFontStyle = FontStyle.Regular;
            btnKickMember.HoverTextColor = Color.White;
            btnKickMember.HoverTransitionDuration = 250;
            btnKickMember.ImageAlign = ContentAlignment.MiddleLeft;
            btnKickMember.ImagePadding = 5;
            btnKickMember.ImageSize = new Size(16, 16);
            btnKickMember.IsRadial = false;
            btnKickMember.IsReadOnly = false;
            btnKickMember.IsToggleButton = false;
            btnKickMember.IsToggled = false;
            btnKickMember.Location = new Point(13, 473);
            btnKickMember.LongPressDurationMS = 1000;
            btnKickMember.Margin = new Padding(3, 4, 3, 4);
            btnKickMember.Name = "btnKickMember";
            btnKickMember.NormalFontStyle = FontStyle.Regular;
            btnKickMember.ParticleColor = Color.FromArgb(200, 200, 200);
            btnKickMember.ParticleCount = 15;
            btnKickMember.PressAnimationScale = 0.97F;
            btnKickMember.PressedBackColor = Color.FromArgb(74, 128, 235);
            btnKickMember.PressedFontStyle = FontStyle.Regular;
            btnKickMember.PressTransitionDuration = 150;
            btnKickMember.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            btnKickMember.RippleColor = Color.FromArgb(255, 255, 255);
            btnKickMember.RippleOpacity = 0.3F;
            btnKickMember.RippleRadiusMultiplier = 0.6F;
            btnKickMember.ShadowBlur = 5;
            btnKickMember.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            btnKickMember.ShadowOffset = new Point(2, 2);
            btnKickMember.ShakeDuration = 500;
            btnKickMember.ShakeIntensity = 5;
            btnKickMember.Size = new Size(115, 31);
            btnKickMember.TabIndex = 11;
            btnKickMember.Text = "Kick Member";
            btnKickMember.TextAlign = ContentAlignment.MiddleCenter;
            btnKickMember.TextColor = Color.White;
            btnKickMember.TooltipText = null;
            btnKickMember.UseAdvancedRendering = true;
            btnKickMember.UseParticles = false;
            btnKickMember.Click += btnKickMember_Click;
            // 
            // lstGroupMembers
            // 
            lstGroupMembers.BackColor = Color.FromArgb(30, 31, 34);
            lstGroupMembers.ForeColor = Color.White;
            lstGroupMembers.FormattingEnabled = true;
            lstGroupMembers.Location = new Point(13, 41);
            lstGroupMembers.Margin = new Padding(3, 4, 3, 4);
            lstGroupMembers.Name = "lstGroupMembers";
            lstGroupMembers.Size = new Size(113, 424);
            lstGroupMembers.TabIndex = 10;
            lstGroupMembers.SelectedIndexChanged += lstGroupMembers_SelectedIndexChanged;
            // 
            // dgvMembers
            // 
            dgvMembers.BackgroundColor = Color.FromArgb(30, 31, 34);
            dgvMembers.BorderStyle = BorderStyle.None;
            dgvMembers.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvMembers.EnableHeadersVisualStyles = false;
            dgvMembers.Location = new Point(3, 481);
            dgvMembers.Name = "dgvMembers";
            dgvMembers.RowHeadersVisible = false;
            dgvMembers.RowHeadersWidth = 51;
            dgvMembers.Size = new Size(133, 13);
            dgvMembers.TabIndex = 9;
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Font = new Font("Tahoma", 9F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label3.ForeColor = Color.White;
            label3.Location = new Point(13, 11);
            label3.Name = "label3";
            label3.Size = new Size(76, 18);
            label3.TabIndex = 8;
            label3.Text = "Members";
            // 
            // panel4
            // 
            panel4.BackColor = SystemColors.WindowFrame;
            panel4.Controls.Add(btnLeaveGroup);
            panel4.Controls.Add(lblGroupNameDisplay);
            panel4.Controls.Add(rightBtn);
            panel4.Location = new Point(273, 71);
            panel4.Name = "panel4";
            panel4.Size = new Size(746, 65);
            panel4.TabIndex = 6;
            // 
            // btnLeaveGroup
            // 
            btnLeaveGroup.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            btnLeaveGroup.AccessibleName = "Leave Group";
            btnLeaveGroup.AutoSizeBasedOnText = false;
            btnLeaveGroup.BackColor = Color.Transparent;
            btnLeaveGroup.BadgeBackColor = Color.Red;
            btnLeaveGroup.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnLeaveGroup.BadgeValue = 0;
            btnLeaveGroup.BadgeValueForeColor = Color.White;
            btnLeaveGroup.BorderColor = Color.Transparent;
            btnLeaveGroup.BorderWidth = 2;
            btnLeaveGroup.ButtonBackColor = Color.Maroon;
            btnLeaveGroup.ButtonImage = null;
            btnLeaveGroup.CanBeep = true;
            btnLeaveGroup.CanGlow = false;
            btnLeaveGroup.CanShake = true;
            btnLeaveGroup.ContextMenuStripEx = null;
            btnLeaveGroup.CornerRadiusBottomLeft = 0;
            btnLeaveGroup.CornerRadiusBottomRight = 0;
            btnLeaveGroup.CornerRadiusTopLeft = 0;
            btnLeaveGroup.CornerRadiusTopRight = 0;
            btnLeaveGroup.CustomCursor = Cursors.Default;
            btnLeaveGroup.DisabledTextColor = Color.FromArgb(150, 150, 150);
            btnLeaveGroup.EnableLongPress = false;
            btnLeaveGroup.EnablePressAnimation = true;
            btnLeaveGroup.EnableRippleEffect = true;
            btnLeaveGroup.EnableShadow = false;
            btnLeaveGroup.EnableTextWrapping = false;
            btnLeaveGroup.Font = new Font("Segoe UI", 9F);
            btnLeaveGroup.GlowColor = Color.FromArgb(100, 255, 255, 255);
            btnLeaveGroup.GlowIntensity = 100;
            btnLeaveGroup.GlowRadius = 20F;
            btnLeaveGroup.GradientBackground = false;
            btnLeaveGroup.GradientColor = Color.FromArgb(114, 168, 255);
            btnLeaveGroup.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            btnLeaveGroup.HintText = null;
            btnLeaveGroup.HoverBackColor = Color.FromArgb(114, 168, 255);
            btnLeaveGroup.HoverFontStyle = FontStyle.Regular;
            btnLeaveGroup.HoverTextColor = Color.White;
            btnLeaveGroup.HoverTransitionDuration = 250;
            btnLeaveGroup.ImageAlign = ContentAlignment.MiddleLeft;
            btnLeaveGroup.ImagePadding = 5;
            btnLeaveGroup.ImageSize = new Size(16, 16);
            btnLeaveGroup.IsRadial = false;
            btnLeaveGroup.IsReadOnly = false;
            btnLeaveGroup.IsToggleButton = false;
            btnLeaveGroup.IsToggled = false;
            btnLeaveGroup.Location = new Point(574, 22);
            btnLeaveGroup.LongPressDurationMS = 1000;
            btnLeaveGroup.Margin = new Padding(3, 4, 3, 4);
            btnLeaveGroup.Name = "btnLeaveGroup";
            btnLeaveGroup.NormalFontStyle = FontStyle.Regular;
            btnLeaveGroup.ParticleColor = Color.FromArgb(200, 200, 200);
            btnLeaveGroup.ParticleCount = 15;
            btnLeaveGroup.PressAnimationScale = 0.97F;
            btnLeaveGroup.PressedBackColor = Color.FromArgb(74, 128, 235);
            btnLeaveGroup.PressedFontStyle = FontStyle.Regular;
            btnLeaveGroup.PressTransitionDuration = 150;
            btnLeaveGroup.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            btnLeaveGroup.RippleColor = Color.FromArgb(255, 255, 255);
            btnLeaveGroup.RippleOpacity = 0.3F;
            btnLeaveGroup.RippleRadiusMultiplier = 0.6F;
            btnLeaveGroup.ShadowBlur = 5;
            btnLeaveGroup.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            btnLeaveGroup.ShadowOffset = new Point(2, 2);
            btnLeaveGroup.ShakeDuration = 500;
            btnLeaveGroup.ShakeIntensity = 5;
            btnLeaveGroup.Size = new Size(115, 31);
            btnLeaveGroup.TabIndex = 12;
            btnLeaveGroup.Text = "Leave Group";
            btnLeaveGroup.TextAlign = ContentAlignment.MiddleCenter;
            btnLeaveGroup.TextColor = Color.White;
            btnLeaveGroup.TooltipText = null;
            btnLeaveGroup.UseAdvancedRendering = true;
            btnLeaveGroup.UseParticles = false;
            btnLeaveGroup.Click += btnLeaveGroup_Click;
            // 
            // lblGroupNameDisplay
            // 
            lblGroupNameDisplay.AutoSize = true;
            lblGroupNameDisplay.Font = new Font("Stencil", 16.2F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblGroupNameDisplay.ForeColor = Color.White;
            lblGroupNameDisplay.Location = new Point(23, 20);
            lblGroupNameDisplay.Name = "lblGroupNameDisplay";
            lblGroupNameDisplay.Size = new Size(63, 33);
            lblGroupNameDisplay.TabIndex = 5;
            lblGroupNameDisplay.Text = "      ";
            // 
            // txtNewMessage
            // 
            txtNewMessage.Location = new Point(117, 5);
            txtNewMessage.Multiline = true;
            txtNewMessage.Name = "txtNewMessage";
            txtNewMessage.Size = new Size(380, 33);
            txtNewMessage.TabIndex = 9;
            txtNewMessage.Visible = false;
            // 
            // btnSaveEdit
            // 
            btnSaveEdit.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            btnSaveEdit.AccessibleName = "Save Changes";
            btnSaveEdit.AutoSizeBasedOnText = false;
            btnSaveEdit.BackColor = Color.Transparent;
            btnSaveEdit.BadgeBackColor = Color.Red;
            btnSaveEdit.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnSaveEdit.BadgeValue = 0;
            btnSaveEdit.BadgeValueForeColor = Color.White;
            btnSaveEdit.BorderColor = Color.Transparent;
            btnSaveEdit.BorderWidth = 2;
            btnSaveEdit.ButtonBackColor = Color.Maroon;
            btnSaveEdit.ButtonImage = null;
            btnSaveEdit.CanBeep = true;
            btnSaveEdit.CanGlow = false;
            btnSaveEdit.CanShake = true;
            btnSaveEdit.ContextMenuStripEx = null;
            btnSaveEdit.CornerRadiusBottomLeft = 0;
            btnSaveEdit.CornerRadiusBottomRight = 0;
            btnSaveEdit.CornerRadiusTopLeft = 0;
            btnSaveEdit.CornerRadiusTopRight = 0;
            btnSaveEdit.CustomCursor = Cursors.Default;
            btnSaveEdit.DisabledTextColor = Color.FromArgb(150, 150, 150);
            btnSaveEdit.EnableLongPress = false;
            btnSaveEdit.EnablePressAnimation = true;
            btnSaveEdit.EnableRippleEffect = true;
            btnSaveEdit.EnableShadow = false;
            btnSaveEdit.EnableTextWrapping = false;
            btnSaveEdit.Font = new Font("Segoe UI", 9F);
            btnSaveEdit.GlowColor = Color.FromArgb(100, 255, 255, 255);
            btnSaveEdit.GlowIntensity = 100;
            btnSaveEdit.GlowRadius = 20F;
            btnSaveEdit.GradientBackground = false;
            btnSaveEdit.GradientColor = Color.FromArgb(114, 168, 255);
            btnSaveEdit.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            btnSaveEdit.HintText = null;
            btnSaveEdit.HoverBackColor = Color.FromArgb(114, 168, 255);
            btnSaveEdit.HoverFontStyle = FontStyle.Regular;
            btnSaveEdit.HoverTextColor = Color.White;
            btnSaveEdit.HoverTransitionDuration = 250;
            btnSaveEdit.ImageAlign = ContentAlignment.MiddleLeft;
            btnSaveEdit.ImagePadding = 5;
            btnSaveEdit.ImageSize = new Size(16, 16);
            btnSaveEdit.IsRadial = false;
            btnSaveEdit.IsReadOnly = false;
            btnSaveEdit.IsToggleButton = false;
            btnSaveEdit.IsToggled = false;
            btnSaveEdit.Location = new Point(97, 66);
            btnSaveEdit.LongPressDurationMS = 1000;
            btnSaveEdit.Margin = new Padding(3, 4, 3, 4);
            btnSaveEdit.Name = "btnSaveEdit";
            btnSaveEdit.NormalFontStyle = FontStyle.Regular;
            btnSaveEdit.ParticleColor = Color.FromArgb(200, 200, 200);
            btnSaveEdit.ParticleCount = 15;
            btnSaveEdit.PressAnimationScale = 0.97F;
            btnSaveEdit.PressedBackColor = Color.FromArgb(74, 128, 235);
            btnSaveEdit.PressedFontStyle = FontStyle.Regular;
            btnSaveEdit.PressTransitionDuration = 150;
            btnSaveEdit.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            btnSaveEdit.RippleColor = Color.FromArgb(255, 255, 255);
            btnSaveEdit.RippleOpacity = 0.3F;
            btnSaveEdit.RippleRadiusMultiplier = 0.6F;
            btnSaveEdit.ShadowBlur = 5;
            btnSaveEdit.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            btnSaveEdit.ShadowOffset = new Point(2, 2);
            btnSaveEdit.ShakeDuration = 500;
            btnSaveEdit.ShakeIntensity = 5;
            btnSaveEdit.Size = new Size(107, 31);
            btnSaveEdit.TabIndex = 8;
            btnSaveEdit.Text = "Save Changes";
            btnSaveEdit.TextAlign = ContentAlignment.MiddleCenter;
            btnSaveEdit.TextColor = Color.White;
            btnSaveEdit.TooltipText = null;
            btnSaveEdit.UseAdvancedRendering = true;
            btnSaveEdit.UseParticles = false;
            btnSaveEdit.Visible = false;
            btnSaveEdit.Click += btnSaveChange_Click;
            // 
            // btnDeleteMessage
            // 
            btnDeleteMessage.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            btnDeleteMessage.AccessibleName = "Delete Message";
            btnDeleteMessage.AutoSizeBasedOnText = false;
            btnDeleteMessage.BackColor = Color.Transparent;
            btnDeleteMessage.BadgeBackColor = Color.Red;
            btnDeleteMessage.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnDeleteMessage.BadgeValue = 0;
            btnDeleteMessage.BadgeValueForeColor = Color.White;
            btnDeleteMessage.BorderColor = Color.Transparent;
            btnDeleteMessage.BorderWidth = 2;
            btnDeleteMessage.ButtonBackColor = Color.Maroon;
            btnDeleteMessage.ButtonImage = null;
            btnDeleteMessage.CanBeep = true;
            btnDeleteMessage.CanGlow = false;
            btnDeleteMessage.CanShake = true;
            btnDeleteMessage.ContextMenuStripEx = null;
            btnDeleteMessage.CornerRadiusBottomLeft = 0;
            btnDeleteMessage.CornerRadiusBottomRight = 0;
            btnDeleteMessage.CornerRadiusTopLeft = 0;
            btnDeleteMessage.CornerRadiusTopRight = 0;
            btnDeleteMessage.CustomCursor = Cursors.Default;
            btnDeleteMessage.DisabledTextColor = Color.FromArgb(150, 150, 150);
            btnDeleteMessage.EnableLongPress = false;
            btnDeleteMessage.EnablePressAnimation = true;
            btnDeleteMessage.EnableRippleEffect = true;
            btnDeleteMessage.EnableShadow = false;
            btnDeleteMessage.EnableTextWrapping = false;
            btnDeleteMessage.Font = new Font("Segoe UI", 9F);
            btnDeleteMessage.GlowColor = Color.FromArgb(100, 255, 255, 255);
            btnDeleteMessage.GlowIntensity = 100;
            btnDeleteMessage.GlowRadius = 20F;
            btnDeleteMessage.GradientBackground = false;
            btnDeleteMessage.GradientColor = Color.FromArgb(114, 168, 255);
            btnDeleteMessage.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            btnDeleteMessage.HintText = null;
            btnDeleteMessage.HoverBackColor = Color.FromArgb(114, 168, 255);
            btnDeleteMessage.HoverFontStyle = FontStyle.Regular;
            btnDeleteMessage.HoverTextColor = Color.White;
            btnDeleteMessage.HoverTransitionDuration = 250;
            btnDeleteMessage.ImageAlign = ContentAlignment.MiddleLeft;
            btnDeleteMessage.ImagePadding = 5;
            btnDeleteMessage.ImageSize = new Size(16, 16);
            btnDeleteMessage.IsRadial = false;
            btnDeleteMessage.IsReadOnly = false;
            btnDeleteMessage.IsToggleButton = false;
            btnDeleteMessage.IsToggled = false;
            btnDeleteMessage.Location = new Point(893, 699);
            btnDeleteMessage.LongPressDurationMS = 1000;
            btnDeleteMessage.Margin = new Padding(3, 4, 3, 4);
            btnDeleteMessage.Name = "btnDeleteMessage";
            btnDeleteMessage.NormalFontStyle = FontStyle.Regular;
            btnDeleteMessage.ParticleColor = Color.FromArgb(200, 200, 200);
            btnDeleteMessage.ParticleCount = 15;
            btnDeleteMessage.PressAnimationScale = 0.97F;
            btnDeleteMessage.PressedBackColor = Color.FromArgb(74, 128, 235);
            btnDeleteMessage.PressedFontStyle = FontStyle.Regular;
            btnDeleteMessage.PressTransitionDuration = 150;
            btnDeleteMessage.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            btnDeleteMessage.RippleColor = Color.FromArgb(255, 255, 255);
            btnDeleteMessage.RippleOpacity = 0.3F;
            btnDeleteMessage.RippleRadiusMultiplier = 0.6F;
            btnDeleteMessage.ShadowBlur = 5;
            btnDeleteMessage.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            btnDeleteMessage.ShadowOffset = new Point(2, 2);
            btnDeleteMessage.ShakeDuration = 500;
            btnDeleteMessage.ShakeIntensity = 5;
            btnDeleteMessage.Size = new Size(123, 31);
            btnDeleteMessage.TabIndex = 7;
            btnDeleteMessage.Text = "Delete Message";
            btnDeleteMessage.TextAlign = ContentAlignment.MiddleCenter;
            btnDeleteMessage.TextColor = Color.White;
            btnDeleteMessage.TooltipText = null;
            btnDeleteMessage.UseAdvancedRendering = true;
            btnDeleteMessage.UseParticles = false;
            btnDeleteMessage.Click += btnDeleteMessage_Click;
            // 
            // btnEditMessage
            // 
            btnEditMessage.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            btnEditMessage.AccessibleName = "Edit Message";
            btnEditMessage.AutoSizeBasedOnText = false;
            btnEditMessage.BackColor = Color.Transparent;
            btnEditMessage.BadgeBackColor = Color.Red;
            btnEditMessage.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            btnEditMessage.BadgeValue = 0;
            btnEditMessage.BadgeValueForeColor = Color.White;
            btnEditMessage.BorderColor = Color.Transparent;
            btnEditMessage.BorderWidth = 2;
            btnEditMessage.ButtonBackColor = Color.Maroon;
            btnEditMessage.ButtonImage = null;
            btnEditMessage.CanBeep = true;
            btnEditMessage.CanGlow = false;
            btnEditMessage.CanShake = true;
            btnEditMessage.ContextMenuStripEx = null;
            btnEditMessage.CornerRadiusBottomLeft = 0;
            btnEditMessage.CornerRadiusBottomRight = 0;
            btnEditMessage.CornerRadiusTopLeft = 0;
            btnEditMessage.CornerRadiusTopRight = 0;
            btnEditMessage.CustomCursor = Cursors.Default;
            btnEditMessage.DisabledTextColor = Color.FromArgb(150, 150, 150);
            btnEditMessage.EnableLongPress = false;
            btnEditMessage.EnablePressAnimation = true;
            btnEditMessage.EnableRippleEffect = true;
            btnEditMessage.EnableShadow = false;
            btnEditMessage.EnableTextWrapping = false;
            btnEditMessage.Font = new Font("Segoe UI", 9F);
            btnEditMessage.GlowColor = Color.FromArgb(100, 255, 255, 255);
            btnEditMessage.GlowIntensity = 100;
            btnEditMessage.GlowRadius = 20F;
            btnEditMessage.GradientBackground = false;
            btnEditMessage.GradientColor = Color.FromArgb(114, 168, 255);
            btnEditMessage.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            btnEditMessage.HintText = null;
            btnEditMessage.HoverBackColor = Color.FromArgb(114, 168, 255);
            btnEditMessage.HoverFontStyle = FontStyle.Regular;
            btnEditMessage.HoverTextColor = Color.White;
            btnEditMessage.HoverTransitionDuration = 250;
            btnEditMessage.ImageAlign = ContentAlignment.MiddleLeft;
            btnEditMessage.ImagePadding = 5;
            btnEditMessage.ImageSize = new Size(16, 16);
            btnEditMessage.IsRadial = false;
            btnEditMessage.IsReadOnly = false;
            btnEditMessage.IsToggleButton = false;
            btnEditMessage.IsToggled = false;
            btnEditMessage.Location = new Point(897, 660);
            btnEditMessage.LongPressDurationMS = 1000;
            btnEditMessage.Margin = new Padding(3, 4, 3, 4);
            btnEditMessage.Name = "btnEditMessage";
            btnEditMessage.NormalFontStyle = FontStyle.Regular;
            btnEditMessage.ParticleColor = Color.FromArgb(200, 200, 200);
            btnEditMessage.ParticleCount = 15;
            btnEditMessage.PressAnimationScale = 0.97F;
            btnEditMessage.PressedBackColor = Color.FromArgb(74, 128, 235);
            btnEditMessage.PressedFontStyle = FontStyle.Regular;
            btnEditMessage.PressTransitionDuration = 150;
            btnEditMessage.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            btnEditMessage.RippleColor = Color.FromArgb(255, 255, 255);
            btnEditMessage.RippleOpacity = 0.3F;
            btnEditMessage.RippleRadiusMultiplier = 0.6F;
            btnEditMessage.ShadowBlur = 5;
            btnEditMessage.ShadowColor = Color.FromArgb(100, 0, 0, 0);
            btnEditMessage.ShadowOffset = new Point(2, 2);
            btnEditMessage.ShakeDuration = 500;
            btnEditMessage.ShakeIntensity = 5;
            btnEditMessage.Size = new Size(115, 31);
            btnEditMessage.TabIndex = 6;
            btnEditMessage.Text = "Edit Message";
            btnEditMessage.TextAlign = ContentAlignment.MiddleCenter;
            btnEditMessage.TextColor = Color.White;
            btnEditMessage.TooltipText = null;
            btnEditMessage.UseAdvancedRendering = true;
            btnEditMessage.UseParticles = false;
            btnEditMessage.Click += btnEditMessage_Click;
            // 
            // panel5
            // 
            panel5.Controls.Add(lstMessages);
            panel5.Controls.Add(txtNewMessage);
            panel5.Controls.Add(btnSaveEdit);
            panel5.Location = new Point(283, 143);
            panel5.Name = "panel5";
            panel5.Size = new Size(720, 507);
            panel5.TabIndex = 7;
            // 
            // lstMessages
            // 
            lstMessages.FormattingEnabled = true;
            lstMessages.Location = new Point(3, -1);
            lstMessages.Name = "lstMessages";
            lstMessages.Size = new Size(717, 504);
            lstMessages.TabIndex = 0;
            lstMessages.SelectedIndexChanged += lstMessages_SelectedIndexChanged;
            // 
            // MainMenu
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(49, 51, 56);
            ClientSize = new Size(1019, 731);
            Controls.Add(btnDeleteMessage);
            Controls.Add(panelMembers);
            Controls.Add(btnEditMessage);
            Controls.Add(panel3);
            Controls.Add(panel2);
            Controls.Add(btnSend);
            Controls.Add(txtMessage);
            Controls.Add(panel1);
            Controls.Add(panel4);
            Controls.Add(panel5);
            FormBorderStyle = FormBorderStyle.None;
            Margin = new Padding(3, 4, 3, 4);
            Name = "MainMenu";
            StartPosition = FormStartPosition.CenterScreen;
            Load += MainMenu_Load;
            panel1.ResumeLayout(false);
            panelJoinGroup.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)dgvAvailableGroups).EndInit();
            panelCreateGroup.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)dgvGroups).EndInit();
            panel2.ResumeLayout(false);
            panel2.PerformLayout();
            panel3.ResumeLayout(false);
            panel3.PerformLayout();
            panelMembers.ResumeLayout(false);
            panelMembers.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvMembers).EndInit();
            panel4.ResumeLayout(false);
            panel4.PerformLayout();
            panel5.ResumeLayout(false);
            panel5.PerformLayout();
            ResumeLayout(false);
        }

        #endregion
        private SiticoneNetCoreUI.SiticoneTextBox txtMessage;
        private SiticoneNetCoreUI.SiticoneImageButton btnSend;
        private MaterialSkin.Controls.MaterialButton btnCreateGroup;
        private MaterialSkin.Controls.MaterialButton btnJoinGroup;
        private Guna.UI2.WinForms.Guna2Button guna2Button1;
        private Guna.UI2.WinForms.Guna2ImageButton guna2ImageButton1;
        private Label label1;
        private Panel panel1;
        private Panel panel2;
        private SiticoneNetCoreUI.SiticoneLabel siticoneLabel1;
        private Panel panel3;
        private SiticoneNetCoreUI.SiticoneImageButton siticoneImageButton2;
        public Label lblUsernameDisplay;
        private SiticoneNetCoreUI.SiticoneImageButton siticoneImageButton3;
        private SiticoneNetCoreUI.SiticoneMenuButton rightBtn;
        private Panel panelMembers;
        private Label label3;
        private SiticoneNetCoreUI.SiticoneButton siticoneButton2;
        private Panel panel4;
        private SiticoneNetCoreUI.SiticoneCloseButton siticoneCloseButton1;
        private DataGridView dgvGroups;
        private SiticoneNetCoreUI.SiticoneButton btnCreate;
        private Panel panelCreateGroup;
        private SiticoneNetCoreUI.SiticoneTextBox txtGroupName;
        private SiticoneNetCoreUI.SiticoneButton btnCancelCreateGroup;
        private SiticoneNetCoreUI.SiticoneButton btnConfirmCreateGroup;
        private Panel panelJoinGroup;
        private DataGridView dgvAvailableGroups;
        private SiticoneNetCoreUI.SiticoneButton btnCancelJoin;
        private SiticoneNetCoreUI.SiticoneButton btnConfirmJoin;
        private Panel panel5;
        private Label lblGroupNameDisplay;
        private ListBox lstMessages;
        private Label lblSelectedGroupID;
        private DataGridView dgvMembers;
        private SiticoneNetCoreUI.SiticoneButton btnSaveEdit;
        private SiticoneNetCoreUI.SiticoneButton btnDeleteMessage;
        private SiticoneNetCoreUI.SiticoneButton btnEditMessage;
        private TextBox txtNewMessage;
        private SiticoneNetCoreUI.SiticoneButton btnKickMember;
        private ListBox lstGroupMembers;
        private SiticoneNetCoreUI.SiticoneButton btnLeaveGroup;
    }
}